export enum CmsPageType {
  ABOUT_US = 'ABOUT_US',
  PRIVACY_POLICY = 'PRIVACY_POLICY',
  TERMS_AND_CONDITIONS = 'TERMS_AND_CONDITIONS',
  SHIPPING_POLICY = 'SHIPPING_POLICY',
  RETURN_POLICY = 'RETURN_POLICY',
  CONTACT_US = 'CONTACT_US',
  CUSTOM_PAGE = 'CUSTOM_PAGE',
}
