export enum ShipmentStatus {
  PENDING = 'PENDING',
  PACKED = 'PACKED',
  READY_FOR_DISPATCH = 'READY_FOR_DISPATCH',
  OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
  DELIVERED = 'DELIVERED',
  FAILED_DELIVERY = 'FAILED_DELIVERY',
}
