export enum ReportType {
  SALES = 'SALES',
  REVENUE = 'REVENUE',
  PRODUCTS = 'PRODUCTS',
  CATEGORIES = 'CATEGORIES',
  BRANDS = 'BRANDS',
  CUSTOMERS = 'CUSTOMERS',
  INVENTORY = 'INVENTORY',
  RETURNS = 'RETURNS',
  SUPPORT = 'SUPPORT',
  MARKETING = 'MARKETING',
}
